runtime: java11
instance_class: F4
env: standart
runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1